"""refresh

Revision ID: 1b11e8daeb37
Revises: 113439925309
Create Date: 2026-05-11 04:02:02.843119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b11e8daeb37'
down_revision: Union[str, Sequence[str], None] = '113439925309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('user_agent', sa.String(length=300), nullable=True))
    op.add_column('refresh_tokens', sa.Column('ip_address', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'ip_address')
    op.drop_column('refresh_tokens', 'user_agent')
    # ### end Alembic commands ###
